
// This file has been generated by the GUI designer. Do not modify.

public partial class YAWIPForm
{
	private global::Gtk.VBox vboxMain;
	
	private global::Gtk.Frame frmGeneral;
	
	private global::Gtk.Table tblGeneral;
	
	private global::Gtk.Label lblFile;
	
	private global::Gtk.Label lblRefreshRate;
	
	private global::Gtk.SpinButton spinRefreshRate;
	
	private global::Gtk.Entry txtFilePath;
	
	private global::Gtk.Label lblGeneral;
	
	private global::Gtk.Notebook notebook;
	
	private global::Gtk.VBox vboxVlc;
	
	private global::Gtk.Label lblVlcExpl;
	
	private global::Gtk.Table tblVlc;
	
	private global::Gtk.Label lblVlcHostname;
	
	private global::Gtk.Label lblVlcPassword;
	
	private global::Gtk.Label lblVlcPort;
	
	private global::Gtk.SpinButton spinVlcPort;
	
	private global::Gtk.Entry txtVlcHostname;
	
	private global::Gtk.Entry txtVlcPassword;
	
	private global::Gtk.Label lblVLC;
	
	private global::Gtk.Table tblSpotify;
	
	private global::Gtk.Label lblSpotify;
	
	private global::Gtk.HBox hboxCommands;
	
	private global::Gtk.Button btnCommand;
	
	private global::Gtk.Button btnReset;
	
	private global::Gtk.Statusbar statusbar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget YAWIPForm
		this.Name = "YAWIPForm";
		this.Title = global::Mono.Unix.Catalog.GetString ("Yet Another What Is Playing");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("YAWIP.OFFICIAL-ICON.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child YAWIPForm.Gtk.Container+ContainerChild
		this.vboxMain = new global::Gtk.VBox ();
		this.vboxMain.Name = "vboxMain";
		this.vboxMain.Spacing = 6;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.frmGeneral = new global::Gtk.Frame ();
		this.frmGeneral.Name = "frmGeneral";
		this.frmGeneral.ShadowType = ((global::Gtk.ShadowType)(1));
		this.frmGeneral.BorderWidth = ((uint)(12));
		// Container child frmGeneral.Gtk.Container+ContainerChild
		this.tblGeneral = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.tblGeneral.Name = "tblGeneral";
		this.tblGeneral.RowSpacing = ((uint)(6));
		this.tblGeneral.ColumnSpacing = ((uint)(6));
		this.tblGeneral.BorderWidth = ((uint)(3));
		// Container child tblGeneral.Gtk.Table+TableChild
		this.lblFile = new global::Gtk.Label ();
		this.lblFile.Name = "lblFile";
		this.lblFile.Xalign = 0F;
		this.lblFile.LabelProp = global::Mono.Unix.Catalog.GetString ("File path:");
		this.tblGeneral.Add (this.lblFile);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tblGeneral [this.lblFile]));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblGeneral.Gtk.Table+TableChild
		this.lblRefreshRate = new global::Gtk.Label ();
		this.lblRefreshRate.Name = "lblRefreshRate";
		this.lblRefreshRate.Xalign = 0F;
		this.lblRefreshRate.LabelProp = global::Mono.Unix.Catalog.GetString ("Refresh rate (ms):");
		this.tblGeneral.Add (this.lblRefreshRate);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tblGeneral [this.lblRefreshRate]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblGeneral.Gtk.Table+TableChild
		this.spinRefreshRate = new global::Gtk.SpinButton (1D, 4294967296D, 1D);
		this.spinRefreshRate.CanFocus = true;
		this.spinRefreshRate.Name = "spinRefreshRate";
		this.spinRefreshRate.Adjustment.PageIncrement = 10D;
		this.spinRefreshRate.ClimbRate = 1D;
		this.spinRefreshRate.Numeric = true;
		this.spinRefreshRate.Value = 1D;
		this.tblGeneral.Add (this.spinRefreshRate);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tblGeneral [this.spinRefreshRate]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblGeneral.Gtk.Table+TableChild
		this.txtFilePath = new global::Gtk.Entry ();
		this.txtFilePath.CanFocus = true;
		this.txtFilePath.Name = "txtFilePath";
		this.txtFilePath.IsEditable = true;
		this.txtFilePath.InvisibleChar = '●';
		this.tblGeneral.Add (this.txtFilePath);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tblGeneral [this.txtFilePath]));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		this.frmGeneral.Add (this.tblGeneral);
		this.lblGeneral = new global::Gtk.Label ();
		this.lblGeneral.Name = "lblGeneral";
		this.lblGeneral.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>General Settings</i>");
		this.lblGeneral.UseMarkup = true;
		this.frmGeneral.LabelWidget = this.lblGeneral;
		this.vboxMain.Add (this.frmGeneral);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.frmGeneral]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.notebook = new global::Gtk.Notebook ();
		this.notebook.CanFocus = true;
		this.notebook.Name = "notebook";
		this.notebook.CurrentPage = 0;
		this.notebook.BorderWidth = ((uint)(9));
		// Container child notebook.Gtk.Notebook+NotebookChild
		this.vboxVlc = new global::Gtk.VBox ();
		this.vboxVlc.Name = "vboxVlc";
		this.vboxVlc.Spacing = 6;
		this.vboxVlc.BorderWidth = ((uint)(6));
		// Container child vboxVlc.Gtk.Box+BoxChild
		this.lblVlcExpl = new global::Gtk.Label ();
		this.lblVlcExpl.Name = "lblVlcExpl";
		this.lblVlcExpl.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Setup the connection to the Telnet Server.</i>");
		this.lblVlcExpl.UseMarkup = true;
		this.lblVlcExpl.Wrap = true;
		this.vboxVlc.Add (this.lblVlcExpl);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vboxVlc [this.lblVlcExpl]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vboxVlc.Gtk.Box+BoxChild
		this.tblVlc = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.tblVlc.Name = "tblVlc";
		this.tblVlc.RowSpacing = ((uint)(6));
		this.tblVlc.ColumnSpacing = ((uint)(6));
		this.tblVlc.BorderWidth = ((uint)(6));
		// Container child tblVlc.Gtk.Table+TableChild
		this.lblVlcHostname = new global::Gtk.Label ();
		this.lblVlcHostname.Name = "lblVlcHostname";
		this.lblVlcHostname.Xalign = 0F;
		this.lblVlcHostname.LabelProp = global::Mono.Unix.Catalog.GetString ("Hostname:");
		this.tblVlc.Add (this.lblVlcHostname);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tblVlc [this.lblVlcHostname]));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblVlc.Gtk.Table+TableChild
		this.lblVlcPassword = new global::Gtk.Label ();
		this.lblVlcPassword.Name = "lblVlcPassword";
		this.lblVlcPassword.Xalign = 0F;
		this.lblVlcPassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
		this.tblVlc.Add (this.lblVlcPassword);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblVlc [this.lblVlcPassword]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblVlc.Gtk.Table+TableChild
		this.lblVlcPort = new global::Gtk.Label ();
		this.lblVlcPort.Name = "lblVlcPort";
		this.lblVlcPort.Xalign = 0F;
		this.lblVlcPort.LabelProp = global::Mono.Unix.Catalog.GetString ("Port:");
		this.tblVlc.Add (this.lblVlcPort);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tblVlc [this.lblVlcPort]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblVlc.Gtk.Table+TableChild
		this.spinVlcPort = new global::Gtk.SpinButton (0D, 65565D, 1D);
		this.spinVlcPort.CanFocus = true;
		this.spinVlcPort.Name = "spinVlcPort";
		this.spinVlcPort.Adjustment.PageIncrement = 10D;
		this.spinVlcPort.ClimbRate = 1D;
		this.spinVlcPort.Numeric = true;
		this.tblVlc.Add (this.spinVlcPort);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblVlc [this.spinVlcPort]));
		w11.TopAttach = ((uint)(1));
		w11.BottomAttach = ((uint)(2));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblVlc.Gtk.Table+TableChild
		this.txtVlcHostname = new global::Gtk.Entry ();
		this.txtVlcHostname.CanFocus = true;
		this.txtVlcHostname.Name = "txtVlcHostname";
		this.txtVlcHostname.IsEditable = true;
		this.txtVlcHostname.InvisibleChar = '●';
		this.tblVlc.Add (this.txtVlcHostname);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblVlc [this.txtVlcHostname]));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblVlc.Gtk.Table+TableChild
		this.txtVlcPassword = new global::Gtk.Entry ();
		this.txtVlcPassword.CanFocus = true;
		this.txtVlcPassword.Name = "txtVlcPassword";
		this.txtVlcPassword.IsEditable = true;
		this.txtVlcPassword.Visibility = false;
		this.txtVlcPassword.InvisibleChar = '●';
		this.tblVlc.Add (this.txtVlcPassword);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblVlc [this.txtVlcPassword]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vboxVlc.Add (this.tblVlc);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxVlc [this.tblVlc]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.notebook.Add (this.vboxVlc);
		// Notebook tab
		this.lblVLC = new global::Gtk.Label ();
		this.lblVLC.Name = "lblVLC";
		this.lblVLC.LabelProp = global::Mono.Unix.Catalog.GetString ("VLC");
		this.notebook.SetTabLabel (this.vboxVlc, this.lblVLC);
		this.lblVLC.ShowAll ();
		// Container child notebook.Gtk.Notebook+NotebookChild
		this.tblSpotify = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.tblSpotify.Name = "tblSpotify";
		this.tblSpotify.RowSpacing = ((uint)(6));
		this.tblSpotify.ColumnSpacing = ((uint)(6));
		this.notebook.Add (this.tblSpotify);
		global::Gtk.Notebook.NotebookChild w16 = ((global::Gtk.Notebook.NotebookChild)(this.notebook [this.tblSpotify]));
		w16.Position = 1;
		// Notebook tab
		this.lblSpotify = new global::Gtk.Label ();
		this.lblSpotify.Name = "lblSpotify";
		this.lblSpotify.LabelProp = global::Mono.Unix.Catalog.GetString ("Spotify");
		this.notebook.SetTabLabel (this.tblSpotify, this.lblSpotify);
		this.lblSpotify.ShowAll ();
		this.vboxMain.Add (this.notebook);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.notebook]));
		w17.Position = 1;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.hboxCommands = new global::Gtk.HBox ();
		this.hboxCommands.Name = "hboxCommands";
		this.hboxCommands.Spacing = 6;
		// Container child hboxCommands.Gtk.Box+BoxChild
		this.btnCommand = new global::Gtk.Button ();
		this.btnCommand.CanFocus = true;
		this.btnCommand.Name = "btnCommand";
		this.btnCommand.UseUnderline = true;
		this.btnCommand.BorderWidth = ((uint)(9));
		this.btnCommand.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.hboxCommands.Add (this.btnCommand);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hboxCommands [this.btnCommand]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hboxCommands.Gtk.Box+BoxChild
		this.btnReset = new global::Gtk.Button ();
		this.btnReset.CanFocus = true;
		this.btnReset.Name = "btnReset";
		this.btnReset.UseUnderline = true;
		this.btnReset.BorderWidth = ((uint)(9));
		this.btnReset.Label = global::Mono.Unix.Catalog.GetString ("_Reset");
		global::Gtk.Image w19 = new global::Gtk.Image ();
		w19.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
		this.btnReset.Image = w19;
		this.hboxCommands.Add (this.btnReset);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hboxCommands [this.btnReset]));
		w20.PackType = ((global::Gtk.PackType)(1));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		this.vboxMain.Add (this.hboxCommands);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hboxCommands]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.statusbar = new global::Gtk.Statusbar ();
		global::Gtk.Tooltips w22 = new Gtk.Tooltips ();
		w22.SetTip (this.statusbar, "The status of YAWIP", "The status of YAWIP");
		this.statusbar.Name = "statusbar";
		this.statusbar.Spacing = 6;
		this.statusbar.HasResizeGrip = false;
		this.vboxMain.Add (this.statusbar);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.statusbar]));
		w23.Position = 3;
		w23.Expand = false;
		w23.Fill = false;
		this.Add (this.vboxMain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 317;
		this.DefaultHeight = 423;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnCommand.Clicked += new global::System.EventHandler (this.OnCommandClick);
		this.btnReset.Clicked += new global::System.EventHandler (this.ResetConfigs);
	}
}
